brasileirao = ('Corinthians','Palmeiras','Santos','Grêmio','Cruzeiro','Flamengo','Vasco','Chapecoense','Atlético-MG','Botafogo','Atlético-PR','Bahia','São Paulo','Fluminense','Sport','Vitória','Coritiba','Avaí','Ponte Preta','Atlético-GO')
print(15*'-=')
print(f'Lista de times do Brasileirão 2017: {brasileirao}')
print(15*'-=')
print('A) 5 primeiros colocados do Brasileirão 2017:',brasileirao[0:6])
print(15*'-=')
print('B) 4 últimos colocados do Brasileirão 2017:',brasileirao[16:])
print(15*'-=')
print('C) Todos os times do Brasileirão 2017 em ordem alfabética:',sorted(brasileirao))
print(15*'-=')
print(f'D) A Chapecoense ficou na {brasileirao.index("Chapecoense")+1}ª posição')
print(15*'-=')